name: Docker image build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  docker:
    strategy:
      matrix:
        database: [quest, clickhouse]
    runs-on: ubuntu-20.04
    environment:
      name: Docker
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Default - Build and push
        uses: docker/build-push-action@v3
        with:
          push: True
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bgp-monitor:latest
      - name: Databases - Build and push
        uses: docker/build-push-action@v3
        with:
          push: True
          build-args: name=${{ secrets.DOCKERHUB_USERNAME }}
          file: ./docker/${{ matrix.database }}/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bgp-monitor:${{ matrix.database }}
