name: Docker image build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-20.04
    environment:
      name: Docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Default - Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          dockerfile: ./docker/Dockerfile
          image: ${{ secrets.DOCKERHUB_USERNAME }}/bgp-monitor
          tags: latest
          context: .