name: documentation

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: ./docker/entrypoint.sh
      - run: PYTHONPATH=$GITHUB_WORKSPACE/bin/ pdoc -o $GITHUB_WORKSPACE/docs/ -t $GITHUB_WORKSPACE/templates/ -d markdown $GITHUB_WORKSPACE/bin/ --favicon https://www.circl.lu/assets/images/circl-logo.png --logo https://www.circl.lu/assets/images/circl-logo.png

      - run: tar --directory docs/ -hcf artifact.tar .
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
  
  deploy:
    needs: build
    runs-on: ubuntu:20.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
